name: my_shopping_mate
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

  # Networking
  http: ^1.2.2

  # Secure Storage
  flutter_secure_storage: ^9.2.2
  
  # Local Storage for Preferences
  shared_preferences: ^2.2.3

  # UI & Theming
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  
  # Utility
  intl: ^0.17.0
  stream_transform: ^2.1.0 # Added for debouncing streams
  uuid: ^3.0.7 # Added for fake repositories


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.2

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true